export default {
  buttonColor: '#3399ff',
  buttonTextColor: '#ffffff',
  buttonHoverColor: '#2389ef',
  buttonActiveColor: '#2288ee',
  buttonActiveTextColor: '#ffffff',
  primaryColor: '#35374B',
  primaryTextColor: '#ffffff',
  secondaryColor: '#344955',
  secondaryTextColor: '#ffffff',
  errorColor: 'orangered',
  successColor: 'green',
  dangerColor: 'orangered',
  dangerTextColor: '#ffffff',
  themeType: 'dark',
  codeBgColor: 'rgba(0,0,0,0.5)',
};
