export default {
  buttonColor: '#3499fe',
  buttonTextColor: '#ffffff',
  buttonHoverColor: '#2b82e0',
  buttonActiveColor: '#4aa3ff',
  buttonActiveTextColor: '#ffffff',
  primaryColor: '#1a1c22',
  primaryColorDark: '#12141a',
  primaryTextColor: '#f1f2f4',
  secondaryColor: '#1c1f27',
  secondaryTextColor: '#f1f2f4',
  textColor: '#e0e0e0',
  borderColor: 'rgba(255,255,255,0.08)',
  errorColor: 'orangered',
  successColor: 'green',
  dangerColor: 'orangered',
  dangerTextColor: '#ffffff',
  linkColor: '#3399ff',
  themeType: 'dark',
  codeBgColor: 'rgba(0,0,0,0.5)',
};
