const FALLBACK_CURRENCY = 'USD';

const FREQUENT_CURRENCIES = ['USD', 'EUR', 'INR', 'GBP', 'SGD', 'AED', 'AUD', 'CAD'];

const ZERO_DECIMAL = new Set([
  'BIF',
  'CLP',
  'CVE',
  'DJF',
  'GNF',
  'HUF',
  'IDR',
  'ISK',
  'JPY',
  'KMF',
  'KRW',
  'MGA',
  'PYG',
  'RWF',
  'UGX',
  'VND',
  'VUV',
  'XAF',
  'XOF',
  'XPF',
]);

const THREE_DECIMAL = new Set(['BHD', 'KWD', 'OMR', 'TND']);

const CURRENCIES = {
  AED: { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham', subunitDigits: 2 },
  AFN: { code: 'AFN', symbol: '؋', name: 'Afghan Afghani', subunitDigits: 2 },
  ALL: { code: 'ALL', symbol: 'L', name: 'Albanian Lek', subunitDigits: 2 },
  AMD: { code: 'AMD', symbol: '֏', name: 'Armenian Dram', subunitDigits: 2 },
  ANG: { code: 'ANG', symbol: 'ƒ', name: 'Netherlands Antillean Guilder', subunitDigits: 2 },
  AOA: { code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza', subunitDigits: 2 },
  ARS: { code: 'ARS', symbol: '$', name: 'Argentine Peso', subunitDigits: 2 },
  AUD: { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', subunitDigits: 2 },
  AWG: { code: 'AWG', symbol: 'ƒ', name: 'Aruban Florin', subunitDigits: 2 },
  AZN: { code: 'AZN', symbol: '₼', name: 'Azerbaijani Manat', subunitDigits: 2 },
  BAM: { code: 'BAM', symbol: 'KM', name: 'Bosnia-Herzegovina Convertible Mark', subunitDigits: 2 },
  BBD: { code: 'BBD', symbol: '$', name: 'Barbadian Dollar', subunitDigits: 2 },
  BDT: { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka', subunitDigits: 2 },
  BGN: { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev', subunitDigits: 2 },
  BHD: { code: 'BHD', symbol: '.د.ب', name: 'Bahraini Dinar', subunitDigits: 3 },
  BIF: { code: 'BIF', symbol: 'FBu', name: 'Burundian Franc', subunitDigits: 0 },
  BMD: { code: 'BMD', symbol: '$', name: 'Bermudian Dollar', subunitDigits: 2 },
  BND: { code: 'BND', symbol: '$', name: 'Brunei Dollar', subunitDigits: 2 },
  BOB: { code: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano', subunitDigits: 2 },
  BRL: { code: 'BRL', symbol: 'R$', name: 'Brazilian Real', subunitDigits: 2 },
  BSD: { code: 'BSD', symbol: '$', name: 'Bahamian Dollar', subunitDigits: 2 },
  BTN: { code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum', subunitDigits: 2 },
  BWP: { code: 'BWP', symbol: 'P', name: 'Botswana Pula', subunitDigits: 2 },
  BYN: { code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble', subunitDigits: 2 },
  BZD: { code: 'BZD', symbol: '$', name: 'Belize Dollar', subunitDigits: 2 },
  CAD: { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar', subunitDigits: 2 },
  CDF: { code: 'CDF', symbol: 'FC', name: 'Congolese Franc', subunitDigits: 2 },
  CHF: { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc', subunitDigits: 2 },
  CLP: { code: 'CLP', symbol: '$', name: 'Chilean Peso', subunitDigits: 0 },
  CNY: { code: 'CNY', symbol: '¥', name: 'Chinese Yuan', subunitDigits: 2 },
  COP: { code: 'COP', symbol: '$', name: 'Colombian Peso', subunitDigits: 2 },
  CRC: { code: 'CRC', symbol: '₡', name: 'Costa Rican Colón', subunitDigits: 2 },
  CUP: { code: 'CUP', symbol: '$', name: 'Cuban Peso', subunitDigits: 2 },
  CVE: { code: 'CVE', symbol: '$', name: 'Cape Verdean Escudo', subunitDigits: 0 },
  CZK: { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna', subunitDigits: 2 },
  DJF: { code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc', subunitDigits: 0 },
  DKK: { code: 'DKK', symbol: 'kr', name: 'Danish Krone', subunitDigits: 2 },
  DOP: { code: 'DOP', symbol: '$', name: 'Dominican Peso', subunitDigits: 2 },
  DZD: { code: 'DZD', symbol: 'د.ج', name: 'Algerian Dinar', subunitDigits: 2 },
  EGP: { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound', subunitDigits: 2 },
  ETB: { code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr', subunitDigits: 2 },
  EUR: { code: 'EUR', symbol: '€', name: 'Euro', subunitDigits: 2 },
  FJD: { code: 'FJD', symbol: '$', name: 'Fijian Dollar', subunitDigits: 2 },
  FKP: { code: 'FKP', symbol: '£', name: 'Falkland Islands Pound', subunitDigits: 2 },
  GBP: { code: 'GBP', symbol: '£', name: 'British Pound', subunitDigits: 2 },
  GEL: { code: 'GEL', symbol: '₾', name: 'Georgian Lari', subunitDigits: 2 },
  GHS: { code: 'GHS', symbol: '₵', name: 'Ghanaian Cedi', subunitDigits: 2 },
  GIP: { code: 'GIP', symbol: '£', name: 'Gibraltar Pound', subunitDigits: 2 },
  GMD: { code: 'GMD', symbol: 'D', name: 'Gambian Dalasi', subunitDigits: 2 },
  GNF: { code: 'GNF', symbol: 'FG', name: 'Guinean Franc', subunitDigits: 0 },
  GTQ: { code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal', subunitDigits: 2 },
  GYD: { code: 'GYD', symbol: '$', name: 'Guyanese Dollar', subunitDigits: 2 },
  HKD: { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar', subunitDigits: 2 },
  HNL: { code: 'HNL', symbol: 'L', name: 'Honduran Lempira', subunitDigits: 2 },
  HTG: { code: 'HTG', symbol: 'G', name: 'Haitian Gourde', subunitDigits: 2 },
  HUF: { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint', subunitDigits: 0 },
  IDR: { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah', subunitDigits: 0 },
  ILS: { code: 'ILS', symbol: '₪', name: 'Israeli New Shekel', subunitDigits: 2 },
  INR: { code: 'INR', symbol: '₹', name: 'Indian Rupee', subunitDigits: 2 },
  IQD: { code: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar', subunitDigits: 2 },
  ISK: { code: 'ISK', symbol: 'kr', name: 'Icelandic Króna', subunitDigits: 0 },
  JMD: { code: 'JMD', symbol: '$', name: 'Jamaican Dollar', subunitDigits: 2 },
  JOD: { code: 'JOD', symbol: 'د.ا', name: 'Jordanian Dinar', subunitDigits: 2 },
  JPY: { code: 'JPY', symbol: '¥', name: 'Japanese Yen', subunitDigits: 0 },
  KES: { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling', subunitDigits: 2 },
  KGS: { code: 'KGS', symbol: 'с', name: 'Kyrgyzstani Som', subunitDigits: 2 },
  KHR: { code: 'KHR', symbol: '៛', name: 'Cambodian Riel', subunitDigits: 2 },
  KMF: { code: 'KMF', symbol: 'CF', name: 'Comorian Franc', subunitDigits: 0 },
  KRW: { code: 'KRW', symbol: '₩', name: 'South Korean Won', subunitDigits: 0 },
  KWD: { code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar', subunitDigits: 3 },
  KYD: { code: 'KYD', symbol: '$', name: 'Cayman Islands Dollar', subunitDigits: 2 },
  KZT: { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge', subunitDigits: 2 },
  LAK: { code: 'LAK', symbol: '₭', name: 'Lao Kip', subunitDigits: 2 },
  LBP: { code: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound', subunitDigits: 2 },
  LKR: { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee', subunitDigits: 2 },
  LRD: { code: 'LRD', symbol: '$', name: 'Liberian Dollar', subunitDigits: 2 },
  LSL: { code: 'LSL', symbol: 'M', name: 'Lesotho Loti', subunitDigits: 2 },
  MAD: { code: 'MAD', symbol: 'د.م.', name: 'Moroccan Dirham', subunitDigits: 2 },
  MDL: { code: 'MDL', symbol: 'L', name: 'Moldovan Leu', subunitDigits: 2 },
  MGA: { code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary', subunitDigits: 0 },
  MKD: { code: 'MKD', symbol: 'ден', name: 'Macedonian Denar', subunitDigits: 2 },
  MMK: { code: 'MMK', symbol: 'K', name: 'Myanmar Kyat', subunitDigits: 2 },
  MNT: { code: 'MNT', symbol: '₮', name: 'Mongolian Tögrög', subunitDigits: 2 },
  MOP: { code: 'MOP', symbol: 'P', name: 'Macanese Pataca', subunitDigits: 2 },
  MRU: { code: 'MRU', symbol: 'UM', name: 'Mauritanian Ouguiya', subunitDigits: 2 },
  MUR: { code: 'MUR', symbol: '₨', name: 'Mauritian Rupee', subunitDigits: 2 },
  MVR: { code: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa', subunitDigits: 2 },
  MWK: { code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha', subunitDigits: 2 },
  MXN: { code: 'MXN', symbol: '$', name: 'Mexican Peso', subunitDigits: 2 },
  MYR: { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit', subunitDigits: 2 },
  MZN: { code: 'MZN', symbol: 'MT', name: 'Mozambican Metical', subunitDigits: 2 },
  NAD: { code: 'NAD', symbol: '$', name: 'Namibian Dollar', subunitDigits: 2 },
  NGN: { code: 'NGN', symbol: '₦', name: 'Nigerian Naira', subunitDigits: 2 },
  NIO: { code: 'NIO', symbol: 'C$', name: 'Nicaraguan Córdoba', subunitDigits: 2 },
  NOK: { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone', subunitDigits: 2 },
  NPR: { code: 'NPR', symbol: '₨', name: 'Nepalese Rupee', subunitDigits: 2 },
  NZD: { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', subunitDigits: 2 },
  OMR: { code: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial', subunitDigits: 3 },
  PAB: { code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa', subunitDigits: 2 },
  PEN: { code: 'PEN', symbol: 'S/', name: 'Peruvian Sol', subunitDigits: 2 },
  PGK: { code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina', subunitDigits: 2 },
  PHP: { code: 'PHP', symbol: '₱', name: 'Philippine Peso', subunitDigits: 2 },
  PKR: { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee', subunitDigits: 2 },
  PLN: { code: 'PLN', symbol: 'zł', name: 'Polish Złoty', subunitDigits: 2 },
  PYG: { code: 'PYG', symbol: '₲', name: 'Paraguayan Guaraní', subunitDigits: 0 },
  QAR: { code: 'QAR', symbol: 'ر.ق', name: 'Qatari Riyal', subunitDigits: 2 },
  RON: { code: 'RON', symbol: 'lei', name: 'Romanian Leu', subunitDigits: 2 },
  RSD: { code: 'RSD', symbol: 'din', name: 'Serbian Dinar', subunitDigits: 2 },
  RUB: { code: 'RUB', symbol: '₽', name: 'Russian Ruble', subunitDigits: 2 },
  RWF: { code: 'RWF', symbol: 'FRw', name: 'Rwandan Franc', subunitDigits: 0 },
  SAR: { code: 'SAR', symbol: 'ر.س', name: 'Saudi Riyal', subunitDigits: 2 },
  SBD: { code: 'SBD', symbol: '$', name: 'Solomon Islands Dollar', subunitDigits: 2 },
  SCR: { code: 'SCR', symbol: '₨', name: 'Seychellois Rupee', subunitDigits: 2 },
  SDG: { code: 'SDG', symbol: 'ج.س.', name: 'Sudanese Pound', subunitDigits: 2 },
  SEK: { code: 'SEK', symbol: 'kr', name: 'Swedish Krona', subunitDigits: 2 },
  SGD: { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar', subunitDigits: 2 },
  SHP: { code: 'SHP', symbol: '£', name: 'Saint Helena Pound', subunitDigits: 2 },
  SLE: { code: 'SLE', symbol: 'Le', name: 'Sierra Leonean Leone', subunitDigits: 2 },
  SLL: { code: 'SLL', symbol: 'Le', name: 'Sierra Leonean Leone (old)', subunitDigits: 2 },
  SOS: { code: 'SOS', symbol: 'Sh.So.', name: 'Somali Shilling', subunitDigits: 2 },
  SRD: { code: 'SRD', symbol: '$', name: 'Surinamese Dollar', subunitDigits: 2 },
  SSP: { code: 'SSP', symbol: '£', name: 'South Sudanese Pound', subunitDigits: 2 },
  STN: { code: 'STN', symbol: 'Db', name: 'São Tomé and Príncipe Dobra', subunitDigits: 2 },
  SVC: { code: 'SVC', symbol: '$', name: 'Salvadoran Colón', subunitDigits: 2 },
  SZL: { code: 'SZL', symbol: 'E', name: 'Swazi Lilangeni', subunitDigits: 2 },
  THB: { code: 'THB', symbol: '฿', name: 'Thai Baht', subunitDigits: 2 },
  TJS: { code: 'TJS', symbol: 'SM', name: 'Tajikistani Somoni', subunitDigits: 2 },
  TMT: { code: 'TMT', symbol: 'm', name: 'Turkmenistani Manat', subunitDigits: 2 },
  TND: { code: 'TND', symbol: 'د.ت', name: 'Tunisian Dinar', subunitDigits: 3 },
  TOP: { code: 'TOP', symbol: 'T$', name: 'Tongan Paʻanga', subunitDigits: 2 },
  TRY: { code: 'TRY', symbol: '₺', name: 'Turkish Lira', subunitDigits: 2 },
  TTD: { code: 'TTD', symbol: '$', name: 'Trinidad and Tobago Dollar', subunitDigits: 2 },
  TWD: { code: 'TWD', symbol: 'NT$', name: 'New Taiwan Dollar', subunitDigits: 2 },
  TZS: { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling', subunitDigits: 2 },
  UAH: { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia', subunitDigits: 2 },
  UGX: { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling', subunitDigits: 0 },
  USD: { code: 'USD', symbol: '$', name: 'US Dollar', subunitDigits: 2 },
  UYU: { code: 'UYU', symbol: '$', name: 'Uruguayan Peso', subunitDigits: 2 },
  UZS: { code: 'UZS', symbol: 'soʼm', name: 'Uzbekistani Som', subunitDigits: 2 },
  VES: { code: 'VES', symbol: 'Bs.', name: 'Venezuelan Bolívar', subunitDigits: 2 },
  VND: { code: 'VND', symbol: '₫', name: 'Vietnamese Đồng', subunitDigits: 0 },
  VUV: { code: 'VUV', symbol: 'VT', name: 'Vanuatu Vatu', subunitDigits: 0 },
  WST: { code: 'WST', symbol: 'T', name: 'Samoan Tālā', subunitDigits: 2 },
  XAF: { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', subunitDigits: 0 },
  XCD: { code: 'XCD', symbol: '$', name: 'East Caribbean Dollar', subunitDigits: 2 },
  XOF: { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', subunitDigits: 0 },
  XPF: { code: 'XPF', symbol: '₣', name: 'CFP Franc', subunitDigits: 0 },
  YER: { code: 'YER', symbol: '﷼', name: 'Yemeni Rial', subunitDigits: 2 },
  ZAR: { code: 'ZAR', symbol: 'R', name: 'South African Rand', subunitDigits: 2 },
  ZMW: { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha', subunitDigits: 2 },
  ZWG: { code: 'ZWG', symbol: 'ZiG', name: 'Zimbabwe Gold', subunitDigits: 2 },
};

const COUNTRY_TO_CURRENCY = {
  AE: 'AED',
  AL: 'ALL',
  AM: 'AMD',
  AO: 'AOA',
  AR: 'ARS',
  AT: 'EUR',
  AU: 'AUD',
  AW: 'AWG',
  AZ: 'AZN',
  BA: 'BAM',
  BB: 'BBD',
  BD: 'BDT',
  BE: 'EUR',
  BG: 'BGN',
  BH: 'BHD',
  BI: 'BIF',
  BM: 'BMD',
  BN: 'BND',
  BO: 'BOB',
  BR: 'BRL',
  BS: 'BSD',
  BT: 'BTN',
  BW: 'BWP',
  BY: 'BYN',
  BZ: 'BZD',
  CA: 'CAD',
  CD: 'CDF',
  CH: 'CHF',
  CL: 'CLP',
  CN: 'CNY',
  CO: 'COP',
  CR: 'CRC',
  CU: 'CUP',
  CV: 'CVE',
  CY: 'EUR',
  CZ: 'CZK',
  DE: 'EUR',
  DJ: 'DJF',
  DK: 'DKK',
  DO: 'DOP',
  DZ: 'DZD',
  EE: 'EUR',
  EG: 'EGP',
  ES: 'EUR',
  ET: 'ETB',
  FI: 'EUR',
  FJ: 'FJD',
  FK: 'FKP',
  FR: 'EUR',
  GB: 'GBP',
  GE: 'GEL',
  GH: 'GHS',
  GI: 'GIP',
  GM: 'GMD',
  GN: 'GNF',
  GR: 'EUR',
  GT: 'GTQ',
  GY: 'GYD',
  HK: 'HKD',
  HN: 'HNL',
  HT: 'HTG',
  HU: 'HUF',
  ID: 'IDR',
  IE: 'EUR',
  IL: 'ILS',
  IN: 'INR',
  IQ: 'IQD',
  IS: 'ISK',
  IT: 'EUR',
  JM: 'JMD',
  JO: 'JOD',
  JP: 'JPY',
  KE: 'KES',
  KG: 'KGS',
  KH: 'KHR',
  KM: 'KMF',
  KR: 'KRW',
  KW: 'KWD',
  KY: 'KYD',
  KZ: 'KZT',
  LA: 'LAK',
  LB: 'LBP',
  LK: 'LKR',
  LR: 'LRD',
  LS: 'LSL',
  LT: 'EUR',
  LU: 'EUR',
  LV: 'EUR',
  MA: 'MAD',
  MD: 'MDL',
  MG: 'MGA',
  MK: 'MKD',
  MM: 'MMK',
  MN: 'MNT',
  MO: 'MOP',
  MR: 'MRU',
  MT: 'EUR',
  MU: 'MUR',
  MV: 'MVR',
  MW: 'MWK',
  MX: 'MXN',
  MY: 'MYR',
  MZ: 'MZN',
  NA: 'NAD',
  NG: 'NGN',
  NI: 'NIO',
  NL: 'EUR',
  NO: 'NOK',
  NP: 'NPR',
  NZ: 'NZD',
  OM: 'OMR',
  PA: 'PAB',
  PE: 'PEN',
  PG: 'PGK',
  PH: 'PHP',
  PK: 'PKR',
  PL: 'PLN',
  PT: 'EUR',
  PY: 'PYG',
  QA: 'QAR',
  RO: 'RON',
  RS: 'RSD',
  RU: 'RUB',
  RW: 'RWF',
  SA: 'SAR',
  SB: 'SBD',
  SC: 'SCR',
  SD: 'SDG',
  SE: 'SEK',
  SG: 'SGD',
  SH: 'SHP',
  SI: 'EUR',
  SK: 'EUR',
  SL: 'SLE',
  SO: 'SOS',
  SR: 'SRD',
  SS: 'SSP',
  ST: 'STN',
  SV: 'SVC',
  SZ: 'SZL',
  TH: 'THB',
  TJ: 'TJS',
  TM: 'TMT',
  TN: 'TND',
  TO: 'TOP',
  TR: 'TRY',
  TT: 'TTD',
  TW: 'TWD',
  TZ: 'TZS',
  UA: 'UAH',
  UG: 'UGX',
  US: 'USD',
  UY: 'UYU',
  UZ: 'UZS',
  VE: 'VES',
  VN: 'VND',
  VU: 'VUV',
  WS: 'WST',
  ZA: 'ZAR',
  ZM: 'ZMW',
  ZW: 'ZWG',

  XK: 'EUR',
  ME: 'EUR',
  MC: 'EUR',
  AD: 'EUR',
  SM: 'EUR',
  VA: 'EUR',
  AX: 'EUR',
  GF: 'EUR',
  GP: 'EUR',
  MQ: 'EUR',
  RE: 'EUR',
  YT: 'EUR',
  BL: 'EUR',
  MF: 'EUR',
  PM: 'EUR',
  TF: 'EUR',
  WF: 'EUR',
  PF: 'XPF',
  NC: 'XPF',
  TD: 'XAF',
  CG: 'XAF',
  GA: 'XAF',
  GQ: 'XAF',
  CF: 'XAF',
  CM: 'XAF',
  TG: 'XOF',
  BJ: 'XOF',
  BF: 'XOF',
  CI: 'XOF',
  GW: 'XOF',
  ML: 'XOF',
  NE: 'XOF',
  SN: 'XOF',
  AG: 'XCD',
  AI: 'XCD',
  DM: 'XCD',
  GD: 'XCD',
  KN: 'XCD',
  LC: 'XCD',
  MS: 'XCD',
  VC: 'XCD',
};

function getCurrencyForCountry(countryCode) {
  if (!countryCode || typeof countryCode !== 'string') {
    return null;
  }

  const upper = countryCode.toUpperCase();
  const currencyCode = COUNTRY_TO_CURRENCY[upper];
  if (!currencyCode) {
    return null;
  }

  return CURRENCIES[currencyCode] || null;
}

function getCurrencySymbol(code) {
  if (!code || typeof code !== 'string') {
    return null;
  }

  const upper = code.toUpperCase();
  const entry = CURRENCIES[upper];
  if (!entry) {
    return null;
  }

  return entry.symbol;
}

function getSubunitDigits(code) {
  if (!code || typeof code !== 'string') {
    return null;
  }

  const upper = code.toUpperCase();
  const entry = CURRENCIES[upper];
  if (!entry) {
    return null;
  }

  return entry.subunitDigits;
}

function getAllCurrencies() {
  const frequentSet = new Set(FREQUENT_CURRENCIES);
  const frequent = [];
  const rest = [];

  for (const [, entry] of Object.entries(CURRENCIES)) {
    const item = {
      code: entry.code,
      symbol: entry.symbol,
      name: entry.name,
    };
    if (frequentSet.has(entry.code)) {
      frequent.push(item);
    } else {
      rest.push(item);
    }
  }

  frequent.sort((a, b) => FREQUENT_CURRENCIES.indexOf(a.code) - FREQUENT_CURRENCIES.indexOf(b.code));
  rest.sort((a, b) => a.name.localeCompare(b.name));

  return [...frequent, ...rest];
}

module.exports = {
  FALLBACK_CURRENCY,
  CURRENCIES,
  COUNTRY_TO_CURRENCY,
  ZERO_DECIMAL,
  THREE_DECIMAL,
  getCurrencyForCountry,
  getCurrencySymbol,
  getSubunitDigits,
  getAllCurrencies,
};
